Repository Git-For-Geeks/Online-Bookstore, pull requests merged in 2022-10, with the labels that each got.

#11 Update README.md
  README.md
Labels: git-for-geeks, hard

#14 navbar improved
  src/index.html
  src/style.css
Labels: easy, git-for-geeks, hacktoberfest-accepted

#16 Edited Audio-books section and redirect.html
  src/index.html
  src/redirect1.html
  src/style.css
Labels: git-for-geeks, hacktoberfest-accepted, medium

#19 Changed the UI of the calculator
  src/calculator.html
Labels: git-for-geeks, hacktoberfest-accepted, medium

#22 headings made visible and removed horizontal scroll
  src/index.html
  src/style.css
Labels: git-for-geeks, hacktoberfest-accepted, medium
